---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: date
  type: datetime
  label: Date Created
  description: ''
  config:
    required: false
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
    export_format: DD-MM-YYYY h:mm A
  hidden: true
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Description
- name: media
  type: image_gallery
  config: {}
  label: Media
- name: categories
  type: tag_list
  default: []
  label: Categories
- name: inventory
  type: include
  config: {}
  template: inventory
  label: Inventory
- name: attributes
  type: include
  config: {}
  template: attributes
  label: Attributes
pages:
- surreal_succulents/content/shop/aeonium/Aeonium 'Velour'.md
