---
label: Product
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: boolean
  name: product
  label: product
- type: text
  name: id
  label: id
