---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: display_image
  type: file
  config:
    maxSize: 64
  label: Display Image
- name: image1
  type: file
  config:
    maxSize: 64
  label: Image 1
- name: image2
  type: file
  config:
    maxSize: 64
  label: Image 2
- name: image3
  type: file
  config:
    maxSize: 64
  label: Image 3
- name: image4
  type: file
  config:
    maxSize: 64
  label: Image 4
- name: image5
  type: file
  config:
    maxSize: 64
  label: Image 5
- name: date
  type: datetime
  label: Date Created
  description: ''
  config:
    required: false
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
    export_format: DD-MM-YYYY h:mm A
  hidden: true
- name: categories
  type: list
  config:
    use_select: true
    min: 
    max: 
    source:
      type: simple
    options:
    - Aeonium
    - Echeveria
    - Sempervivum
    - Crassula
    - Aloe
    - Trailing Succulents
    - Surreal Hybrids
    - Others
    - Pots and Extras
    - Agave
    - Haworthia
    - Sedum
    - Surreal Collections
    - Sedeveria
    - Rare Plant Fair
    - Terrariums
    - Geometric Pots
    - Terracotta Pots
    - Large Specimens
  label: Categories
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Description
- name: inventory
  type: include
  config: {}
  template: inventory
  label: Inventory
- name: attributes
  type: include
  config: {}
  template: attributes
  label: Attributes
pages:
- surreal_succulents/content/shop/aeonium/Aeonium 'Velour'.md
- surreal_succulents/content/shop/aeonium/aeonium-fiesta.md
