---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: date
  type: datetime
  label: Date Created
  description: ''
  config:
    required: false
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
    export_format: DD-MM-YYYY h:mm A
  hidden: true
- type: text
  name: id
  label: Product ID
  config:
    required: true
    min: 4
    max: 8
- name: product
  type: boolean
  label: Product
- name: sku
  type: text
  config:
    required: false
  label: SKU
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Description
- name: media
  type: image_gallery
  config: {}
  label: Media
- name: categories
  type: tag_list
  default: []
  label: Categories
- name: hardiness
  type: select
  default: []
  config:
    required: false
    options:
    - Green
    - Amber
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Hardiness
- name: price
  type: text
  config:
    required: false
  label: Price
  default: "£"
- name: manage_stock_
  type: boolean
  label: Manage Stock?
- name: stock
  type: number
  label: Stock
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
  showOnly:
    field: manage_stock_
    value: true
pages:
- surreal_succulents/content/shop/aeonium/Aeonium 'Velour'.md
