---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: tremenheere/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: tremenheere/content/stockorder
  label: Stockorder
  create: all
  match: "**/*"
- type: directory
  path: tremenheere/content/productapi
  label: Productapi
  create: all
  match: "**/*"
- type: directory
  path: tremenheere/content/neworder
  label: Neworder
  create: all
  match: "**/*"
upload_dir: tremenheere/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: cd tremenheere && hugo server -D -E -F --port 8080 --bind
    0.0.0.0 --renderToDisk -d public
version: 0.81.0
